services:
  front:
    build: ./front-end
    ports:
      - "80:80"
    depends_on:
      - back
    environment:
      VITE_API_URL: /api

  back:
    build: ./back-end
    depends_on:
      - db
    environment:
      CONNECTION_HOST: db
      CONNECTION_USER: root
      CONNECTION_PASSWORD: ${DB_PASSWORD}
      CONNECTION_DATABASE: evenshare

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: evenshare
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
